Server:
	sudo javac Server.java
	sudo java -cp "/Applications/NetBeans/NetBeans 8.2.app/Contents/Resources/NetBeans/ide/modules/ext/mysql-connector-java-8.0.12.jar:/Users/eliothmonroy/Documents/Github/AplicacionesRedes/Practicas/Practica2-Carrito" Server

Cliente:
	javac Cliente.java
	sudo java Cliente
clean:
	sudo rm -f *.class